version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    volumes:
      - ./frontend/src:/frontend/src
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - default
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_PORT=${API_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes:
      - ./backend/src:/backend/src
    restart: always
    networks:
      - default
  db:
    container_name: db
    image: mysql:8.0.21
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    volumes:
      - ./backend/src/db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./backend/src/db/seeder.sql:/docker-entrypoint-initdb.d/seeder.sql
    cap_add:
      - SYS_NICE
    networks:
      - default
networks:
  default:
    driver: bridge

