version: '3.9'
services:
  frontend:
    build: ./
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:7000"]
      timeout: 10s
      retries: 5
    volumes:
      - ./src:/frontend/src
    restart: always
